### ISSUE TITLE
Display controller detection missing display 128x32

### ISSUE THREAD

**Issue by Lilithet** [bitbank2/OneBitDisplay#11]
Display controller type OLED_SSD1306_3C for 128x32 (white) is missing.

Possible solution:

Line 1305:
  else if ( u == 3 ||u == 6 || u == 7) // 7=128x64(rare),6=128x64 display, 3=smaller
changed to 
  else if (u == 1 || u == 3 ||u == 6 || u == 7) // 7=128x64(rare),6=128x64 display, 3=smaller, 1=128x32

**Comment by bitbank2** [comment]
These values are unreliable for determining the display type.
