### ISSUE TITLE
Non I2C Displays do not work on Core 0 of ESP32

### ISSUE THREAD

**Issue by Lilithet** [bitbank2/OneBitDisplay#12]
When using both cores on an ESP32 the non I2C Displays do not work properly when setting text from core 0. Core 1 on the other hand works fine, as do displays connected to the I2C hardware pins.

Messy example code:
`// OneBitDisplay library for I2C multi-display
#include <OneBitDisplay.h>

// Use -1 for the Wire library default pins
// or specify the pin numbers to use with the Wire library or bit banging on any GPIO pins
// These are reversed because I did straight-through wiring for my SSD1306
// and it has the 4-pin header as GND,VCC,SCL,SDA, but the LCD1 connector is
// GND,VCC,SDA,SCL
#define LCD1_SDA_PIN 19
#define LCD1_SCL_PIN 18

//Encoder Data Pins
#define Encoder_PinA 16
#define Encoder_PinB 17

#define SDA_PIN 21
#define SCL_PIN 22
// Set this to -1 to disable or the GPIO pin number connected to the reset
// line of your display if it requires an external reset
#define RESET_PIN -1
// let ss_oled figure out the display address (-1)
#define OLED_ADDR 0x3C
#define OLED_ADDR2 0x3D
// don't rotate the display
#define FLIP180 0
// don't invert the display
#define INVERT 0
// Bit-Bang the I2C bus
#define USE_HW_I2C 0

// Change these if you're using different OLED displays
#define MY_OLED1 OLED_128x32
#define MY_OLED2 OLED_128x32

// 2 copies of the SSOLED structure. Each structure is about 56 bytes
// There is no limit to the number of simultaneous displays which can be controlled by ss_oled
OBDISP obd[2];

TaskHandle_t Task1;
TaskHandle_t Task2;

int lastRead;
int lastRead2;
int lastState;
int lastState2;
int Counter;

char * t;
char cstr[8];

void Task1code( void * parameter) {
  for (;;)
  {
    //Serial.println("Task 1");
    if (lastRead != digitalRead(Encoder_PinA))
      lastRead ^= 1;
    if (lastRead2 != digitalRead(Encoder_PinB))
      lastRead2 ^= 1;
      
    //lastRead == (int)digitalRead(Encoder_PinA);
    //lastRead2 == (int)digitalRead(Encoder_PinB);

    if (lastState != lastRead || lastState2 != lastRead2)
    {
      if ((lastState > lastRead && lastState2 == 1) || (lastState < lastRead && lastState2 == 0))
        Counter++;
      else if ((lastState > lastRead && lastState2 == 0) || (lastState < lastRead && lastState2 == 1))
        Counter--;

      lastState = lastRead;
      lastState2 = lastRead2;
    }
    //Serial.println("Task 1 finished");
  }
}

void Task2code( void * parameter) {
  for (;;)
  {
    //Serial.println("Task 2");
    if (lastRead == 1)
      t = "HIGH";
    else
      t = "LOW ";

    obdWriteString(&obd[0], 0, 0, 0, t, FONT_STRETCHED, 0, 1);

    if (lastRead2 == 1)
      t = "HIGH";
    else
      t = "LOW ";

    obdWriteString(&obd[0], 0, 0, 2, t, FONT_STRETCHED, 0, 1);

    sprintf(cstr, "%03d.%04d", Counter / 10000, Counter % 10000);
    obdWriteString(&obd[1], 0, 0, 0, (char *)cstr, FONT_STRETCHED, 0, 1);
    //delay(50);
    //Serial.println("Task 2 finished");
  }
}

void setup() {

  //Serial.begin(115200);

  lastRead = 1;
  lastRead2 = 0;
  lastState = 0;
  lastState2 = 1;
  Counter = 10000;

  pinMode(Encoder_PinA, INPUT);
  pinMode(Encoder_PinB, INPUT);
  //char *msgs[] = {(char *)"SSD1306 @ 0x3C", (char *)"SSD1306 @ 0x3D", (char *)"SH1106 @ 0x3C", (char *)"SH1106 @ 0x3D"};
  int rc;
  // The I2C SDA/SCL pins set to -1 means to use the default Wire library
  // If pins were specified, they would be bit-banged in software
  // This isn't inferior to hw I2C and in fact allows you to go faster on certain CPUs
  // The reset pin is optional and I've only seen it needed on larger OLEDs (2.4")
  //    that can be configured as either SPI or I2C
  //
  // obdI2CInit(OBDISP *, type, oled_addr, rotate180, invert, bWire, SDA_PIN, SCL_PIN, RESET_PIN, speed)

  delay(100);
  rc = obdI2CInit(&obd[0], MY_OLED1, OLED_ADDR, FLIP180, INVERT, 1, -1, -1, RESET_PIN, 400000L); // use standard I2C bus at 400Khz
  if (rc != OLED_NOT_FOUND)
  {
    obdFill(&obd[0], 0, 1);
    //obdWriteString(&obd[0], 0, 0, 0, (char *)"Display1", FONT_STRETCHED, 0, 1);
    //obdWriteString(&obd[0], 0, 0, 0, (char *)rc, FONT_STRETCHED, 0, 1);
    //obdWriteString(&obd[0], 0, 0, 2, (char *)"x0", FONT_STRETCHED, 0, 1);
  }
  delay(10);
  rc = obdI2CInit(&obd[1], MY_OLED2, OLED_ADDR, FLIP180, INVERT, 0, LCD1_SDA_PIN, LCD1_SCL_PIN, RESET_PIN, 400000L); // use standard I2C bus at 400Khz
  if (rc != OLED_NOT_FOUND)
  {
    delay(10);
    obdFill(&obd[1], 0, 1);
    //obdSetTextWrap(&obd[1], 1);
    //obdWriteString(&obd[1], 0, 0, 0, (char *)"Display2", FONT_STRETCHED, 0, 1);
    //obdWriteString(&obd[1], 0, 0, 2, (char *)"123.45678900", FONT_STRETCHED, 0, 1);
  }

  xTaskCreatePinnedToCore(
    Task1code, /* Function to implement the task */
    "Task1", /* Name of the task */
    10000,  /* Stack size in words */
    NULL,  /* Task input parameter */
    1,  /* Priority of the task */
    &Task1,  /* Task handle. */
    1); /* Core where the task should run */
  delay(500);

  xTaskCreatePinnedToCore(
    Task2code, /* Function to implement the task */
    "Task2", /* Name of the task */
    10000,  /* Stack size in words */
    NULL,  /* Task input parameter */
    1,  /* Priority of the task */
    &Task2,  /* Task handle. */
    0); /* Core where the task should run */
  delay(500);

} /* setup() */

//free loop task, because I said so.
void loop() {
  vTaskDelete(NULL);  /* loop() */
}`

switching Task2code with Task1code works properly.

**Comment by bitbank2** [comment]
Sorry, I just saw this. If the problem still exists, open a new issue.
