### ISSUE TITLE
odbWriteString broken in releases > 1.5.0

### ISSUE THREAD

**Issue by cyberman54** [bitbank2/OneBitDisplay#13]
I'm using odbWriteString to draw text on display in my code, which is based on v1.5.0.
After updating the library to 1.7.1 character drawn in the last column is not displayed an more, and newlines happen.
I assume that something with the cursor logic is going wrong.
Roll back to 1.5.0 solves the problem.

**Comment by cyberman54** [comment]
I suggested a [PR](https://github.com/bitbank2/OneBitDisplay/pull/14) to fix this

**Comment by bitbank2** [comment]
merged
