### ISSUE TITLE
Characters are sometimes drawn with 1px left shift

### ISSUE THREAD

**Issue by cyberman54** [bitbank2/OneBitDisplay#15]
Characters drawn with `odbWriteString()` are sometimes placed with a left offset of 1px on the display.
I added two pictures which show the problem. Compare the placement of the "SF7" in the pictures.
This happenes accidentially, i can't see any context which could trigger this effect.
I did not see this effect with the former _ss_oled_ library, using my same application code.

The shown characters were drawn by calling `odbWriteString()` with param `int x = -1`, meaning continue writing from the last cursor position, and param `int iScroll = 0`.

The effect seems to occur with all font sizes.

![IMG_20200913_123611](https://user-images.githubusercontent.com/10289836/93016013-4943e880-f5be-11ea-8e34-e19d19939c76.jpg)
![IMG_20200913_123619](https://user-images.githubusercontent.com/10289836/93016016-506af680-f5be-11ea-84a1-4563d1ea25aa.jpg)

**Comment by bitbank2** [comment]
Please retest on the latest and open a new issue if it still exists.
