### ISSUE TITLE
fatal error: BitBang_I2C.h: No such file or directory

### ISSUE THREAD

**Issue by selevo** [bitbank2/OneBitDisplay#2]
I install lib  and  load simple_demo_avr...
But....
\arduino 1.8.5 AVRDUDE original\portable\sketchbook\libraries\OneBitDisplay\src/OneBitDisplay.h:4:25: fatal error: BitBang_I2C.h: No such file or directory

 #include <BitBang_I2C.h>

**Comment by bitbank2** [comment]
BitBang_I2C is a dependent library that must be installed. If you install OneBitDisplay through the library manager, it will get installed automatically. If not, you can install it manually.
