### ISSUE TITLE
rlottie widget for OneBitDisplay

### ISSUE THREAD

**Issue by ajsb85** [bitbank2/OneBitDisplay#21]
Allows to use rlottie animations in OneBitDisplay

You can use [Samsung/rlottie](https://github.com/Samsung/rlottie) library with C-api header

Best regards.

Ref:
https://github.com/Samsung/rlottie/issues/484

**Comment by bitbank2** [comment]
I would prefer if you write your own code to render rlottie graphics into a buffer and then use my library to display those pixels. I don't plan on integrating external features like this.
