### ISSUE TITLE
Platformio Library Manager doesn't install lib any more

### ISSUE THREAD

**Issue by cyberman54** [bitbank2/OneBitDisplay#22]
With Platformio it's no longer possible to reference this lib by name `bitbank2/OneBitDisplay`:

```
Library Manager: Installing bitbank2/OneBitDisplay
Warning! Could not find the package with 'bitbank2/OneBitDisplay' requirements for your system 'windows_amd64'
```

If referencing by URL it works:
`https://github.com/bitbank2/OneBitDisplay`

Strange: Platformio Lib Manager show email address in lib name:
`XaXXXXXXX@gmail.com/OneBitDisplay @ ^1.10.0`

**Comment by bitbank2** [comment]
Sorry, I don't use PlatformIO and not sure why it stopped working.
