### ISSUE TITLE
Mistakenly recognized SH1106 128x64 as SSD1306

### ISSUE THREAD

**Issue by vinhcatba** [bitbank2/OneBitDisplay#23]
I tried few examples, all of them have 2-column left shift problem. In my experience, this left-shifting is because of the RAM difference between SH1106 (132x64) and SSD1306 (128x64). When I print the return value of `obdI2CInit()` to the Serial, I got `0`, which means `OLED_SSD1306_3C`.

So, I changed `iType` to `OLED_132x64`, as in **OneBitDisplay.h**. Everything worked fine, but I still got `OLED_SSD1306_3C` as the return value of `obdI2CInit()`.

Although this issue will not break anything (for now), **as long as you use oled type `OLED_132x64` for the SSH1106 128x64**, but it's not right neither.

**Comment by bitbank2** [comment]
I should probably remove the auto-detect because the various controllers don't return unique results.
