### ISSUE TITLE
Error compiling for board Generic STM32F103C series.

### ISSUE THREAD

**Issue by murty206** [bitbank2/OneBitDisplay#28]
Hello,

Thank you for this great library I'm trying to use with STM32 BluePill since it has more ram and flash but I'm getting this error. What should I do?
BitBang_I2C.cpp:565:44: error: no matching function for call to 'TwoWire::begin(uint8_t&, uint8_t&)
Thank you.

**Comment by bitbank2** [comment]
I just tried to build it with the latest code on Arduino STM32F1 target and it worked. What setup are you using?
