### ISSUE TITLE
obdPower for the ONE_BIT_DISPLAY C++ class?

### ISSUE THREAD

**Issue by graynk** [bitbank2/OneBitDisplay#33]
Hi! Love your library, thank you for your work.

Am I understanding correctly that if I'm using `ONE_BIT_DISPLAY` C++ class, then there's no API for turning the screen off and I should use pure `obdX` methods instead (or add a wrapper myself)? As far as I see it there's no way to get `_obd`  to pass to `obdPower()` and there's no wrapper for it. Is this by design?

**Comment by cyberman54** [comment]
I miss the power feature, too, and this currently is blocking me to migrate to the 2.x c++ version of the lib.

**Comment by cyberman54** [comment]
This can be closed now, thanks!

https://github.com/bitbank2/OneBitDisplay/pull/34
