### ISSUE TITLE
Animation in 2.x

### ISSUE THREAD

**Issue by combs** [bitbank2/OneBitDisplay#37]
Hello! Thank you for making this library. It is very fast!

I am working on a reimplementation of `oled_animator` in Python to support >4096 frames and to work around library licensing limitations. (it is quite early yet: https://github.com/combs/Python_OneBitDisplay_Animator )

As part of this, I noticed that the output from `oled_animation_demo` is garbled on my setup when compiling with 2.1.0:

- Arduino Uno clone
- SSD1306 128x64 and SH1106 128x64

![oled](https://user-images.githubusercontent.com/6174018/187266919-8c0bc0bc-8118-4d23-a217-69005f039fc1.gif)

1.11.0 works well (once I hardcode the screen type and reduce I2C speed).
2.0.0 does not compile.
2.0.1 is also garbled.

Therefore, I suspect a breaking change introduced with 2.x may be responsible. Do you have any pointers (ha ha) as to what might have changed? I am curious if `obdSetPosition` perhaps works differently now. 

Many thanks,
Chris

Update: I am able to get a partially correct display on SSD1306 by updating each call to `obdSetPosition` within `obdPlayAnimFrame`:

before:

```
       obdSetPosition(pOBD, i & iWidthMask, (i >> iWidthShift), 1);
```

after:

```
       obdSetPosition(pOBD, i & iWidthMask, (i >> iWidthShift) << 3, 1);
```

It seems like `obdSetPosition` accepts Y in 1px increments now instead of 8px. So that's not too big of a change. But the rest of the screen is filled with random sparkles and some frames seem to render entirely within the first Y-block row. Will keep chewing. 

![oled2](https://user-images.githubusercontent.com/6174018/187271986-26c04b57-64b2-4810-a584-c1e229d2f14f.gif)

**Comment by bitbank2** [comment]
I'm sorry I just noticed this issue. I have actually removed all of the animation code because it had some flaws and was a lower priority than the newer features. I would say that it's best to keep a fork of my older library and try to fix the issues yourself.
