### ISSUE TITLE
1px rendering error using obdWriteString

### ISSUE THREAD

**Issue by cyberman54** [bitbank2/OneBitDisplay#4]
I am using `obdWriteString()` to display text on a SSD1306 oled display, which is refreshed with 25fps. I oberved a slightly line flickering, and discovered that this is caused by sometimes a line with text is shifted 1xp back and forth (to left, than back to right).

Since i'm using the same code with former ssoled library, i guess this behaviour is caused by the library.

**Comment by bitbank2** [comment]
Please provide sample code to reproduce this problem. I have not seen this problem on the latest code.

**Comment by cyberman54** [comment]
https://github.com/cyberman54/ESP32-Paxcounter/blob/development/src/display.cpp

**Comment by bitbank2** [comment]
Please provide a SIMPLE/MINIMAL example which shows the problem. Your code above is several layers deep and is inconclusive.
