### ISSUE TITLE
Buffered text with obdWriteString doesn't work on the lower half of a 128x128 display

### ISSUE THREAD

**Issue by ed-wigg** [bitbank2/OneBitDisplay#5]
`obdWriteDataBlock` has 1024 hard coded as the maximum length of the screen buffer so buffered text the lower half of a 128x128 display is ignored. I fixed it in my case by increasing the maximum length to 2048 (and setting the bit mask to 2047), but there may be a better solution.

**Comment by bitbank2** [comment]
I just made major changes to the library to support virtual displays of any size. This required that I fix all of the areas which had hard coded values of 1023. Please do a git pull from the experimental branch and verify that it's fixed. I will be doing an official release shortly of this latest code.

**Comment by ed-wigg** [comment]
The experimental branch works correctly.

**Comment by bitbank2** [comment]
Great - thanks for letting me know.
